# https://github.com/kubernetes-sigs/kustomize/issues/4593
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: mimir
name: mimir-distributed
namespace: monitoring
repo: https://grafana.github.io/helm-charts
values: values.yaml