nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.tools.brentgruber.com
        paths:
          - path: /
            pathType: Prefix
    tls:

metaMonitoring:
  serviceMonitor:
    enabled: true
  grafanaAgent:
    enabled: true
    installOperator: true
    metrics:
      additionalRemoteWriteConfigs:
        - url: "http://mimir-nginx.monitoring.svc:80/api/v1/push"