containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

kubeProxyReplacement: strict

eni:
  enabled: true

nodePort:
  enabled: true
externalIPs:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.42.0.0/16"


operator:
  replicas: 1

# Enable Hubble
hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  
  relay:
    enabled: true
  
  ui:
    enabled: true