containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock

kubeProxyReplacement: strict

# Enable Hubble
hubble:
  enabled: true
  listenAddress: ":4244"
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  
  relay:
    enabled: true
  
  ui:
    enabled: true