resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.5/install.yaml
  - namespace.yaml
  - ingress.yaml

# https://github.com/kubernetes-sigs/kustomize/issues/3265
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--insecure --disable-auth"
    target:
      kind: Deployment
      name: argo-server

namespace: argo