resources:
  - namespace.yaml

helmChartInflationGenerator:
  - chartRepoUrl: https://helm.releases.hashicorp.com
    chartHome: hashicorp
    chartName: consul
    releaseName: consul
    releaseNamespace: consul

patches:
  - patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
    target:
      kind: PodDisruptionBudget

namespace: consul