ingress:
  enabled: true
  hosts:
    - grafana.tools.brentgruber.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

grafana.ini:
  [auth.anonymous]
  enabled = true
  org_role = Viewer