resources:
  - namespace.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - project.yaml

patchesStrategicMerge:
  - patch.yaml
  - configmap.yaml

namespace: argocd