resources:
  - namespace.yaml
  #- ingress.yaml
  - network-policy.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.7/manifests/install.yaml

patches:
  - patch.yaml
  - configmap.yaml

namespace: argocd