apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    namespace: gitea
    server: 'https://kubernetes.default.svc'
  source:
    path: '.'
    repoURL: 'https://github.com/BrentGruberOrg/gitea-deploy.git'
    targetRevision: main
  project: brentgruberorg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true