apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: grafana
    repoURL: 'https://github.com/BrentGruberOrg/tools-deploy.git'
    targetRevision: HEAD
  project: brentgruberorg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true