apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: consul
    server: 'https://kubernetes.default.svc'
  source:
    path: consul
    repoURL: 'https://github.com/BrentGruberOrg/tools-deploy.git'
    targetRevision: HEAD
  project: brentgruberorg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true